import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/sonner";
import SiteLayout from "@/components/layout/site-layout";
import {auth} from "@/auth";
import {getTotalCartItem} from "@/feature/cart/action";
import {CartInitializer} from "@/components/cart/cart-initializer";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const poppinsFonts = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const initialCount = session ? await getTotalCartItem(session.user.id) : 0;
  return (
    <html lang="en">
      <body className={`${poppinsFonts.className} antialiased`}>
        <CartInitializer initialCount={initialCount} />
        <SiteLayout header={<Header />} footer={<Footer />}>
          {" "}
          {children}
        </SiteLayout>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
