import type {Metadata} from "next";
import Dashboard from "@/components/admin/dashboard";

export const metadata: Metadata = {
  title: "admin dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Dashboard>{children}</Dashboard>;
}
